micronaut:
  application:
    name: veiculosService
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
rabbitmq.uri: amqp://localhost:5672
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
