micronaut:
  application:
    name: veiculosService
datasources:
  default:
    url: jdbc:mysql://myapp-mysql:3306/veiculos
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL

rabbitmq.uri: amqp://localhost:5672

netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    packages-to-scan:
      - 'br.com.curso.infrastructure.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true